// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccessRuleCondition : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The field to evaluate in the condition</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Field { get; set; }
#nullable restore
#else
        public string Field { get; set; }
#endif
        /// <summary>The comparison operator to use. Not all field types support all operators.</summary>
        public global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleConditionOperator? Operator { get; set; }
        /// <summary>The value to compare against. Can be null for terminal operators like &apos;present&apos; and &apos;not_present&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition"/> and sets the default values.
        /// </summary>
        public AccessRuleCondition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field", n => { Field = n.GetStringValue(); } },
                { "operator", n => { Operator = n.GetEnumValue<global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleConditionOperator>(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value>(global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field", Field);
            writer.WriteEnumValue<global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleConditionOperator>("operator", Operator);
            writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="bool"/>, <see cref="double"/>, <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition_valueMember1"/>, <see cref="int"/>, <see cref="string"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class AccessRuleCondition_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition_valueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition_valueMember1? AccessRuleConditionValueMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition_valueMember1 AccessRuleConditionValueMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="bool"/></summary>
            public bool? Boolean { get; set; }
            /// <summary>Composed type representation for type <see cref="double"/></summary>
            public double? Double { get; set; }
            /// <summary>Composed type representation for type <see cref="int"/></summary>
            public int? Integer { get; set; }
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition.AccessRuleCondition_value();
                if(parseNode.GetBoolValue() is bool booleanValue)
                {
                    result.Boolean = booleanValue;
                }
                else if(parseNode.GetDoubleValue() is double doubleValue)
                {
                    result.Double = doubleValue;
                }
                else if(parseNode.GetIntValue() is int integerValue)
                {
                    result.Integer = integerValue;
                }
                else if(parseNode.GetStringValue() is string stringValue)
                {
                    result.String = stringValue;
                }
                else {
                    result.AccessRuleConditionValueMember1 = new global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition_valueMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(AccessRuleConditionValueMember1 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(AccessRuleConditionValueMember1);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Boolean != null)
                {
                    writer.WriteBoolValue(null, Boolean);
                }
                else if(Double != null)
                {
                    writer.WriteDoubleValue(null, Double);
                }
                else if(Integer != null)
                {
                    writer.WriteIntValue(null, Integer);
                }
                else if(String != null)
                {
                    writer.WriteStringValue(null, String);
                }
                else {
                    writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.AccessRuleCondition_valueMember1>(null, AccessRuleConditionValueMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
