// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>
    /// Account&apos;s knowledge management and search capabilities. See [Knowledge](#knowledge)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AccountSettingsKnowledgeObject : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The default_search_filters_brands property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSearchFiltersBrands { get; set; }
#nullable restore
#else
        public string DefaultSearchFiltersBrands { get; set; }
#endif
        /// <summary>The default_search_filters_categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSearchFiltersCategories { get; set; }
#nullable restore
#else
        public string DefaultSearchFiltersCategories { get; set; }
#endif
        /// <summary>The default_search_filters_external_content_sources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSearchFiltersExternalContentSources { get; set; }
#nullable restore
#else
        public string DefaultSearchFiltersExternalContentSources { get; set; }
#endif
        /// <summary>The default_search_filters_locales property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSearchFiltersLocales { get; set; }
#nullable restore
#else
        public string DefaultSearchFiltersLocales { get; set; }
#endif
        /// <summary>The default_search_filters_sections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultSearchFiltersSections { get; set; }
#nullable restore
#else
        public string DefaultSearchFiltersSections { get; set; }
#endif
        /// <summary>The generative_answers property</summary>
        public bool? GenerativeAnswers { get; set; }
        /// <summary>The require_article_templates property</summary>
        public bool? RequireArticleTemplates { get; set; }
        /// <summary>The search_articles property</summary>
        public bool? SearchArticles { get; set; }
        /// <summary>The search_community_posts property</summary>
        public bool? SearchCommunityPosts { get; set; }
        /// <summary>The search_external_content property</summary>
        public bool? SearchExternalContent { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccountSettingsKnowledgeObject"/> and sets the default values.
        /// </summary>
        public AccountSettingsKnowledgeObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AccountSettingsKnowledgeObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.AccountSettingsKnowledgeObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zendesk.OpenApiClient.Models.AccountSettingsKnowledgeObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "default_search_filters_brands", n => { DefaultSearchFiltersBrands = n.GetStringValue(); } },
                { "default_search_filters_categories", n => { DefaultSearchFiltersCategories = n.GetStringValue(); } },
                { "default_search_filters_external_content_sources", n => { DefaultSearchFiltersExternalContentSources = n.GetStringValue(); } },
                { "default_search_filters_locales", n => { DefaultSearchFiltersLocales = n.GetStringValue(); } },
                { "default_search_filters_sections", n => { DefaultSearchFiltersSections = n.GetStringValue(); } },
                { "generative_answers", n => { GenerativeAnswers = n.GetBoolValue(); } },
                { "require_article_templates", n => { RequireArticleTemplates = n.GetBoolValue(); } },
                { "search_articles", n => { SearchArticles = n.GetBoolValue(); } },
                { "search_community_posts", n => { SearchCommunityPosts = n.GetBoolValue(); } },
                { "search_external_content", n => { SearchExternalContent = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("default_search_filters_brands", DefaultSearchFiltersBrands);
            writer.WriteStringValue("default_search_filters_categories", DefaultSearchFiltersCategories);
            writer.WriteStringValue("default_search_filters_external_content_sources", DefaultSearchFiltersExternalContentSources);
            writer.WriteStringValue("default_search_filters_locales", DefaultSearchFiltersLocales);
            writer.WriteStringValue("default_search_filters_sections", DefaultSearchFiltersSections);
            writer.WriteBoolValue("generative_answers", GenerativeAnswers);
            writer.WriteBoolValue("require_article_templates", RequireArticleTemplates);
            writer.WriteBoolValue("search_articles", SearchArticles);
            writer.WriteBoolValue("search_community_posts", SearchCommunityPosts);
            writer.WriteBoolValue("search_external_content", SearchExternalContent);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
