// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutomationObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>An object describing what the automation will do. See [Actions reference](/documentation/ticketing/reference-guides/actions-reference)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zendesk.OpenApiClient.Models.ActionObject>? Actions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zendesk.OpenApiClient.Models.ActionObject> Actions { get; set; }
#endif
        /// <summary>Whether the automation is active</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object that describes the conditions under which the automation will execute. See [Conditions reference](/documentation/ticketing/reference-guides/conditions-reference)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.ConditionsObject? Conditions { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.ConditionsObject Conditions { get; set; }
#endif
        /// <summary>The time the automation was created</summary>
        public DateTimeOffset? CreatedAt { get; private set; }
        /// <summary>If true, the automation is a default automation</summary>
        public bool? Default { get; private set; }
        /// <summary>Automatically assigned when created</summary>
        public long? Id { get; private set; }
        /// <summary>The position of the automation which specifies the order it will be executed</summary>
        public int? Position { get; set; }
        /// <summary>The raw title of the automation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawTitle { get; private set; }
#nullable restore
#else
        public string RawTitle { get; private set; }
#endif
        /// <summary>The title of the automation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The time of the last update of the automation</summary>
        public DateTimeOffset? UpdatedAt { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AutomationObject"/> and sets the default values.
        /// </summary>
        public AutomationObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AutomationObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.AutomationObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zendesk.OpenApiClient.Models.AutomationObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetCollectionOfObjectValues<global::Soenneker.Zendesk.OpenApiClient.Models.ActionObject>(global::Soenneker.Zendesk.OpenApiClient.Models.ActionObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "active", n => { Active = n.GetBoolValue(); } },
                { "conditions", n => { Conditions = n.GetObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.ConditionsObject>(global::Soenneker.Zendesk.OpenApiClient.Models.ConditionsObject.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "raw_title", n => { RawTitle = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zendesk.OpenApiClient.Models.ActionObject>("actions", Actions);
            writer.WriteBoolValue("active", Active);
            writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.ConditionsObject>("conditions", Conditions);
            writer.WriteIntValue("position", Position);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
