// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilteredSearchCondition"/>, <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf2"/>, <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf3"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CustomObjectRecordFilterExpression : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilteredSearchCondition"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilteredSearchCondition? CustomObjectRecordFilteredSearchCondition { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilteredSearchCondition CustomObjectRecordFilteredSearchCondition { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf2? CustomObjectRecordFilterExpressionOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf2 CustomObjectRecordFilterExpressionOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf3? CustomObjectRecordFilterExpressionOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf3 CustomObjectRecordFilterExpressionOneOf3 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpression"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpression CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpression();
            if("CustomObjectRecordFilterExpressionOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomObjectRecordFilterExpressionOneOf2 = new global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf2();
            }
            else if("CustomObjectRecordFilterExpressionOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomObjectRecordFilterExpressionOneOf3 = new global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf3();
            }
            else if("CustomObjectRecordFilteredSearchCondition".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.CustomObjectRecordFilteredSearchCondition = new global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilteredSearchCondition();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomObjectRecordFilteredSearchCondition != null)
            {
                return CustomObjectRecordFilteredSearchCondition.GetFieldDeserializers();
            }
            else if(CustomObjectRecordFilterExpressionOneOf2 != null)
            {
                return CustomObjectRecordFilterExpressionOneOf2.GetFieldDeserializers();
            }
            else if(CustomObjectRecordFilterExpressionOneOf3 != null)
            {
                return CustomObjectRecordFilterExpressionOneOf3.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CustomObjectRecordFilteredSearchCondition != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilteredSearchCondition>(null, CustomObjectRecordFilteredSearchCondition);
            }
            else if(CustomObjectRecordFilterExpressionOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf2>(null, CustomObjectRecordFilterExpressionOneOf2);
            }
            else if(CustomObjectRecordFilterExpressionOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordFilterExpressionOneOf3>(null, CustomObjectRecordFilterExpressionOneOf3);
            }
        }
    }
}
#pragma warning restore CS0618
