// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestBasic"/>, <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestComplex"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilteredSearchCustomObjectRecordsRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestBasic"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestBasic? CustomObjectRecordsFilteredSearchRequestBasic { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestBasic CustomObjectRecordsFilteredSearchRequestBasic { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestComplex"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestComplex? CustomObjectRecordsFilteredSearchRequestComplex { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestComplex CustomObjectRecordsFilteredSearchRequestComplex { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.FilteredSearchCustomObjectRecordsRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.FilteredSearchCustomObjectRecordsRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Zendesk.OpenApiClient.Models.FilteredSearchCustomObjectRecordsRequest();
            result.CustomObjectRecordsFilteredSearchRequestBasic = new global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestBasic();
            result.CustomObjectRecordsFilteredSearchRequestComplex = new global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestComplex();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CustomObjectRecordsFilteredSearchRequestBasic != null || CustomObjectRecordsFilteredSearchRequestComplex != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CustomObjectRecordsFilteredSearchRequestBasic, CustomObjectRecordsFilteredSearchRequestComplex);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.CustomObjectRecordsFilteredSearchRequestBasic>(null, CustomObjectRecordsFilteredSearchRequestBasic, CustomObjectRecordsFilteredSearchRequestComplex);
        }
    }
}
#pragma warning restore CS0618
