// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>
    /// Response for incremental export of custom object records. See [Custom Object Records](/api-reference/custom-data/custom-objects/custom_object_records/) for detailed information about custom object record properties.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IncrementalCustomObjectRecordsResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Cursor value for the next page. Use this value for the cursor parameter in the next request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AfterCursor { get; set; }
#nullable restore
#else
        public string AfterCursor { get; set; }
#endif
        /// <summary>URL to fetch the next page of results. Null if this is the last page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AfterUrl { get; set; }
#nullable restore
#else
        public string AfterUrl { get; set; }
#endif
        /// <summary>Cursor value for the previous page. Null if this is the first page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BeforeCursor { get; set; }
#nullable restore
#else
        public string BeforeCursor { get; set; }
#endif
        /// <summary>URL to fetch the previous page of results. Null if this is the first page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BeforeUrl { get; set; }
#nullable restore
#else
        public string BeforeUrl { get; set; }
#endif
        /// <summary>Array of custom object records that have changed since the start time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseCustomObjectRecordsItem>? CustomObjectRecords { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseCustomObjectRecordsItem> CustomObjectRecords { get; set; }
#endif
        /// <summary>Applied filters for the export</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseFilter? Filter { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseFilter Filter { get; set; }
#endif
        /// <summary>Metadata about the export operation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseMeta? Meta { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseMeta Meta { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponse"/> and sets the default values.
        /// </summary>
        public IncrementalCustomObjectRecordsResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "after_cursor", n => { AfterCursor = n.GetStringValue(); } },
                { "after_url", n => { AfterUrl = n.GetStringValue(); } },
                { "before_cursor", n => { BeforeCursor = n.GetStringValue(); } },
                { "before_url", n => { BeforeUrl = n.GetStringValue(); } },
                { "custom_object_records", n => { CustomObjectRecords = n.GetCollectionOfObjectValues<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseCustomObjectRecordsItem>(global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseCustomObjectRecordsItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "filter", n => { Filter = n.GetObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseFilter>(global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseFilter.CreateFromDiscriminatorValue); } },
                { "meta", n => { Meta = n.GetObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseMeta>(global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseMeta.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("after_cursor", AfterCursor);
            writer.WriteStringValue("after_url", AfterUrl);
            writer.WriteStringValue("before_cursor", BeforeCursor);
            writer.WriteStringValue("before_url", BeforeUrl);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseCustomObjectRecordsItem>("custom_object_records", CustomObjectRecords);
            writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseFilter>("filter", Filter);
            writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.IncrementalCustomObjectRecordsResponseMeta>("meta", Meta);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
