// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ItamAsset"/>, <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItemBranch2"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ItamAssetBulkJobRequestJobItemsItem : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ItamAsset"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.ItamAsset? ItamAsset { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.ItamAsset ItamAsset { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItemBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItemBranch2? ItamAssetBulkJobRequestJobItemsItemBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItemBranch2 ItamAssetBulkJobRequestJobItemsItemBranch2 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItem();
            if("ItamAsset".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ItamAsset = new global::Soenneker.Zendesk.OpenApiClient.Models.ItamAsset();
            }
            else if("ItamAssetBulkJobRequestJobItemsItemBranch2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ItamAssetBulkJobRequestJobItemsItemBranch2 = new global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItemBranch2();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ItamAsset != null)
            {
                return ItamAsset.GetFieldDeserializers();
            }
            else if(ItamAssetBulkJobRequestJobItemsItemBranch2 != null)
            {
                return ItamAssetBulkJobRequestJobItemsItemBranch2.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ItamAsset != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.ItamAsset>(null, ItamAsset);
            }
            else if(ItamAssetBulkJobRequestJobItemsItemBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.ItamAssetBulkJobRequestJobItemsItemBranch2>(null, ItamAssetBulkJobRequestJobItemsItemBranch2);
            }
        }
    }
}
#pragma warning restore CS0618
