// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ObjectTriggerObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>An array of actions the trigger does when its conditions are met. See [Actions reference](/documentation/ticketing/reference-guides/actions-reference)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Zendesk.OpenApiClient.Models.TriggerActionObject>? Actions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Zendesk.OpenApiClient.Models.TriggerActionObject> Actions { get; set; }
#endif
        /// <summary>Whether the trigger is active</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An object that describes the circumstances under which the trigger performs its actions. See [Conditions reference](/documentation/ticketing/reference-guides/conditions-reference)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Zendesk.OpenApiClient.Models.TriggerConditionsObject? Conditions { get; set; }
#nullable restore
#else
        public global::Soenneker.Zendesk.OpenApiClient.Models.TriggerConditionsObject Conditions { get; set; }
#endif
        /// <summary>The time the trigger was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; private set; }
#nullable restore
#else
        public string CreatedAt { get; private set; }
#endif
        /// <summary>Always false for object triggers</summary>
        public bool? Default { get; private set; }
        /// <summary>The description of the trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Automatically assigned when created</summary>
        public long? Id { get; private set; }
        /// <summary>Position of the trigger, determines the order they will execute in</summary>
        public int? Position { get; set; }
        /// <summary>The raw format of the title of the trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawTitle { get; set; }
#nullable restore
#else
        public string RawTitle { get; set; }
#endif
        /// <summary>The title of the trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The time of the last update of the trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; private set; }
#nullable restore
#else
        public string UpdatedAt { get; private set; }
#endif
        /// <summary>The url of the trigger</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; private set; }
#nullable restore
#else
        public string Url { get; private set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ObjectTriggerObject"/> and sets the default values.
        /// </summary>
        public ObjectTriggerObject()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ObjectTriggerObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Zendesk.OpenApiClient.Models.ObjectTriggerObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Zendesk.OpenApiClient.Models.ObjectTriggerObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actions", n => { Actions = n.GetCollectionOfObjectValues<global::Soenneker.Zendesk.OpenApiClient.Models.TriggerActionObject>(global::Soenneker.Zendesk.OpenApiClient.Models.TriggerActionObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "active", n => { Active = n.GetBoolValue(); } },
                { "conditions", n => { Conditions = n.GetObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.TriggerConditionsObject>(global::Soenneker.Zendesk.OpenApiClient.Models.TriggerConditionsObject.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "raw_title", n => { RawTitle = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Zendesk.OpenApiClient.Models.TriggerActionObject>("actions", Actions);
            writer.WriteBoolValue("active", Active);
            writer.WriteObjectValue<global::Soenneker.Zendesk.OpenApiClient.Models.TriggerConditionsObject>("conditions", Conditions);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("position", Position);
            writer.WriteStringValue("raw_title", RawTitle);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
