// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>The string representation of remote authentication type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RemoteAuthenticationObjectAuthModeName
    {
        [EnumMember(Value = "saml")]
        #pragma warning disable CS1591
        Saml,
        #pragma warning restore CS1591
        [EnumMember(Value = "jwt")]
        #pragma warning disable CS1591
        Jwt,
        #pragma warning restore CS1591
        [EnumMember(Value = "oidc")]
        #pragma warning disable CS1591
        Oidc,
        #pragma warning restore CS1591
    }
}
