// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum RoleAuthenticationObjectSecurityPolicyName
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "low")]
        #pragma warning disable CS1591
        Low,
        #pragma warning restore CS1591
        [EnumMember(Value = "medium")]
        #pragma warning disable CS1591
        Medium,
        #pragma warning restore CS1591
        [EnumMember(Value = "high")]
        #pragma warning disable CS1591
        High,
        #pragma warning restore CS1591
        [EnumMember(Value = "recommended")]
        #pragma warning disable CS1591
        Recommended,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
