// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>**Deprecated.** This field is no longer in use. Existing support addresses will return their previously stored value. New support addresses will return `&quot;unknown&quot;`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    [Obsolete("")]
    public enum SupportAddressObjectCnameStatus
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
