// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>The type of support that handled the ticket</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TicketCreateVoicemailTicketInputSupportType
    {
        [EnumMember(Value = "agent")]
        #pragma warning disable CS1591
        Agent,
        #pragma warning restore CS1591
        [EnumMember(Value = "ai_agent")]
        #pragma warning disable CS1591
        AiAgent,
        #pragma warning restore CS1591
    }
}
