// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>The state of the ticket.If your account has activated custom ticket statuses, this is the ticket&apos;sstatus category. See [custom ticket statuses](#custom-ticket-statuses)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TicketCreateVoicemailTicketInputStatus
    {
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        NewValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "hold")]
        #pragma warning disable CS1591
        Hold,
        #pragma warning restore CS1591
        [EnumMember(Value = "solved")]
        #pragma warning disable CS1591
        Solved,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed")]
        #pragma warning disable CS1591
        Closed,
        #pragma warning restore CS1591
    }
}
