// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Models
{
    /// <summary>Indicates whether the identity is owned or shared. Only returned to non-end-user callers.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserIdentityObjectOwnership
    {
        [EnumMember(Value = "owned")]
        #pragma warning disable CS1591
        Owned,
        #pragma warning restore CS1591
        [EnumMember(Value = "shared")]
        #pragma warning disable CS1591
        Shared,
        #pragma warning restore CS1591
    }
}
