// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Api.V2.Channels.Voice.Agents.Item.Users.Item.Display;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Channels.Voice.Agents.Item.Users.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\channels\voice\agents\{agentId}\users\{userId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The display property</summary>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Channels.Voice.Agents.Item.Users.Item.Display.DisplayRequestBuilder Display
        {
            get => new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Channels.Voice.Agents.Item.Users.Item.Display.DisplayRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Channels.Voice.Agents.Item.Users.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/channels/voice/agents/{agentId}/users/{userId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Channels.Voice.Agents.Item.Users.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/channels/voice/agents/{agentId}/users/{userId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
