// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Automations.Active
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\automations\active
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActiveRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Automations.Active.ActiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/automations/active", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Automations.Active.ActiveRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActiveRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/automations/active", rawUrl)
        {
        }
        /// <summary>
        /// Lists all active automations.#### Allowed For* Agents#### Available ParametersYou can pass in any combination of the following optional filters:| Name       | Type   | Comment| ---------- | ------ | -------| sort_by    | string | Possible values are &quot;alphabetical&quot;, &quot;created_at&quot;, &quot;updated_at&quot;, &quot;usage_1h&quot;, &quot;usage_24h&quot;, or &quot;usage_7d&quot;. Defaults to &quot;position&quot;| sort_order | string | One of &quot;asc&quot; or &quot;desc&quot;. Defaults to &quot;asc&quot; for alphabetical and position sort, &quot;desc&quot; for all others#### SideloadsThe following sideloads are supported:| Name             | Will sideload| ---------------- | -------------| app_installation | The app installation that requires each automation, if present| permissions      | The permissions for each automation| usage_1h         | The number of tickets processed by an automation in the past hour| usage_24h        | The number of tickets processed by an automation in the past day| usage_7d         | The number of tickets processed by an automation in the past week| usage_30d        | The number of tickets processed by an automation in the past thirty days
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AutomationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.AutomationsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.AutomationsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.AutomationsResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.AutomationsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists all active automations.#### Allowed For* Agents#### Available ParametersYou can pass in any combination of the following optional filters:| Name       | Type   | Comment| ---------- | ------ | -------| sort_by    | string | Possible values are &quot;alphabetical&quot;, &quot;created_at&quot;, &quot;updated_at&quot;, &quot;usage_1h&quot;, &quot;usage_24h&quot;, or &quot;usage_7d&quot;. Defaults to &quot;position&quot;| sort_order | string | One of &quot;asc&quot; or &quot;desc&quot;. Defaults to &quot;asc&quot; for alphabetical and position sort, &quot;desc&quot; for all others#### SideloadsThe following sideloads are supported:| Name             | Will sideload| ---------------- | -------------| app_installation | The app installation that requires each automation, if present| permissions      | The permissions for each automation| usage_1h         | The number of tickets processed by an automation in the past hour| usage_24h        | The number of tickets processed by an automation in the past day| usage_7d         | The number of tickets processed by an automation in the past week| usage_30d        | The number of tickets processed by an automation in the past thirty days
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Automations.Active.ActiveRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Automations.Active.ActiveRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Automations.Active.ActiveRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
