// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\groups\available_agents
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Available_agentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Available_agentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/groups/available_agents{?include_boundary_indicators*,include_item_cursors*,page*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Available_agentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/groups/available_agents{?include_boundary_indicators*,include_item_cursors*,page*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of all agents available to be added to groups. The current user must have permission to edit group memberships.#### Pagination* Cursor paginationSee [Pagination](/api-reference/introduction/pagination/).Returns a maximum of 1000 records per page.#### Allowed For* Admins* Agents with permission to edit group memberships
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.AvailableAgentsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zendesk.OpenApiClient.Models.ListAvailableAgents403Response">When receiving a 403 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.AvailableAgentsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder.Available_agentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.AvailableAgentsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder.Available_agentsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "403", global::Soenneker.Zendesk.OpenApiClient.Models.ListAvailableAgents403Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.AvailableAgentsResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.AvailableAgentsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of all agents available to be added to groups. The current user must have permission to edit group memberships.#### Pagination* Cursor paginationSee [Pagination](/api-reference/introduction/pagination/).Returns a maximum of 1000 records per page.#### Allowed For* Admins* Agents with permission to edit group memberships
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder.Available_agentsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder.Available_agentsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Groups.Available_agents.Available_agentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of all agents available to be added to groups. The current user must have permission to edit group memberships.#### Pagination* Cursor paginationSee [Pagination](/api-reference/introduction/pagination/).Returns a maximum of 1000 records per page.#### Allowed For* Admins* Agents with permission to edit group memberships
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Available_agentsRequestBuilderGetQueryParameters 
        {
            /// <summary>When true, includes `has_more` indicator in the cursor pagination response meta.Only valid with cursor pagination (page[size], page[after], page[before]).</summary>
            [QueryParameter("include_boundary_indicators")]
            public bool? IncludeBoundaryIndicators { get; set; }
            /// <summary>When true, includes cursor values for each item in the cursor pagination response.Only valid with cursor pagination (page[size], page[after], page[before]).</summary>
            [QueryParameter("include_item_cursors")]
            public bool? IncludeItemCursors { get; set; }
            /// <summary>Cursor-based pagination parameters (JSON:API style).Supports nested parameters:- `page[size]` - Number of records per page (default varies by endpoint, typically 100)- `page[after]` - Cursor token to fetch records after this position- `page[before]` - Cursor token to fetch records before this positionExample: `?page[size]=50&amp;page[after]=eyJvIjoiaWQiLCJ2IjoiYVFFPSJ9`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page")]
            public string? Page { get; set; }
#nullable restore
#else
            [QueryParameter("page")]
            public string Page { get; set; }
#endif
            /// <summary>Field to sort results by. Prefix with `-` for descending order.When used with cursor pagination, this determines the cursor ordering.Example: `?sort=name` or `?sort=-created_at`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
