// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\views\show_many
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Show_manyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Show_manyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/views/show_many?ids={ids}{&active*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Show_manyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/views/show_many?ids={ids}{&active*}", rawUrl)
        {
        }
        /// <summary>
        /// #### Allowed For* Agents#### SideloadsThe following sideloads are supported:| Name             | Will sideload| ---------------- | -------------| app_installation | The app installation that requires each view, if present| permissions      | The permissions for each view
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.ViewsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.ViewsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder.Show_manyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.ViewsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder.Show_manyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.ViewsResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.ViewsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// #### Allowed For* Agents#### SideloadsThe following sideloads are supported:| Name             | Will sideload| ---------------- | -------------| app_installation | The app installation that requires each view, if present| permissions      | The permissions for each view
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder.Show_manyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder.Show_manyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Views.Show_many.Show_manyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// #### Allowed For* Agents#### SideloadsThe following sideloads are supported:| Name             | Will sideload| ---------------- | -------------| app_installation | The app installation that requires each view, if present| permissions      | The permissions for each view
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Show_manyRequestBuilderGetQueryParameters 
        {
            /// <summary>Only active views if true, inactive views if false</summary>
            [QueryParameter("active")]
            public bool? Active { get; set; }
            /// <summary>List of view&apos;s ids separated by commas.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("ids")]
            public string? Ids { get; set; }
#nullable restore
#else
            [QueryParameter("ids")]
            public string Ids { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
