// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\macros\{macroId}\apply
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/macros/{macroId}/apply{?normalize_comment*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/macros/{macroId}/apply{?normalize_comment*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the changes the macro would make to a ticket. It doesn&apos;t actuallychange a ticket. You can use the response data in a subsequent API callto the [Tickets](/api-reference/ticketing/tickets/tickets/) endpoint to update the ticket.The response includes only the ticket fields that would be changed by themacro. To get the full ticket object after the macro is applied,see [Show Ticket After Changes](#show-ticket-after-changes).#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.MacroApplyTicketResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.MacroApplyTicketResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder.ApplyRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.MacroApplyTicketResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder.ApplyRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.MacroApplyTicketResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.MacroApplyTicketResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the changes the macro would make to a ticket. It doesn&apos;t actuallychange a ticket. You can use the response data in a subsequent API callto the [Tickets](/api-reference/ticketing/tickets/tickets/) endpoint to update the ticket.The response includes only the ticket fields that would be changed by themacro. To get the full ticket object after the macro is applied,see [Show Ticket After Changes](#show-ticket-after-changes).#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder.ApplyRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder.ApplyRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Macros.Item.Apply.ApplyRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns the changes the macro would make to a ticket. It doesn&apos;t actuallychange a ticket. You can use the response data in a subsequent API callto the [Tickets](/api-reference/ticketing/tickets/tickets/) endpoint to update the ticket.The response includes only the ticket fields that would be changed by themacro. To get the full ticket object after the macro is applied,see [Show Ticket After Changes](#show-ticket-after-changes).#### Allowed For* Agents
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ApplyRequestBuilderGetQueryParameters 
        {
            /// <summary>If true, normalizes the newline formatting of the macro&apos;s comment to more closely match the formatting produced by the ticket comment editor</summary>
            [QueryParameter("normalize_comment")]
            public bool? NormalizeComment { get; set; }
        }
    }
}
#pragma warning restore CS0618
