// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Triggers.Update_many
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\triggers\update_many
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Update_manyRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Triggers.Update_many.Update_manyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Update_manyRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/triggers/update_many", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Triggers.Update_many.Update_manyRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Update_manyRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/triggers/update_many", rawUrl)
        {
        }
        /// <summary>
        /// Updates the position or the active status of multiple ticket triggers. Any additional properties are ignored.#### Allowed For* Agents#### Request ParametersThe PUT request expects a `triggers` object that lists the ticket triggers to update.A maximum of 100 ticket triggers can be updated per request.Each ticket trigger may have the following properties:| Name        | Mandatory | Description| --------    | --------- | -----------| id          | yes       | The ID of the ticket trigger to update| position    | no        | The new position of the ticket trigger| active      | no        | The active status of the ticket trigger (true or false)| category_id | no        | The ID of the new category the ticket trigger is to be moved to#### Example Request```js{  &quot;triggers&quot;: [    {&quot;id&quot;: 25, &quot;position&quot;: 3},    {&quot;id&quot;: 23, &quot;position&quot;: 5},    {&quot;id&quot;: 27, &quot;position&quot;: 9},    {&quot;id&quot;: 22, &quot;position&quot;: 7}  ]}```
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.TriggersResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.TriggersResponse?> PutAsync(global::Soenneker.Zendesk.OpenApiClient.Models.TriggerBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.TriggersResponse> PutAsync(global::Soenneker.Zendesk.OpenApiClient.Models.TriggerBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.TriggersResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.TriggersResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Updates the position or the active status of multiple ticket triggers. Any additional properties are ignored.#### Allowed For* Agents#### Request ParametersThe PUT request expects a `triggers` object that lists the ticket triggers to update.A maximum of 100 ticket triggers can be updated per request.Each ticket trigger may have the following properties:| Name        | Mandatory | Description| --------    | --------- | -----------| id          | yes       | The ID of the ticket trigger to update| position    | no        | The new position of the ticket trigger| active      | no        | The active status of the ticket trigger (true or false)| category_id | no        | The ID of the new category the ticket trigger is to be moved to#### Example Request```js{  &quot;triggers&quot;: [    {&quot;id&quot;: 25, &quot;position&quot;: 3},    {&quot;id&quot;: 23, &quot;position&quot;: 5},    {&quot;id&quot;: 27, &quot;position&quot;: 9},    {&quot;id&quot;: 22, &quot;position&quot;: 7}  ]}```
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::Soenneker.Zendesk.OpenApiClient.Models.TriggerBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::Soenneker.Zendesk.OpenApiClient.Models.TriggerBulkUpdateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Triggers.Update_many.Update_manyRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Triggers.Update_many.Update_manyRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Triggers.Update_many.Update_manyRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
