// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.Options;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\user_fields\{userFieldId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserFieldItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The optionsPath property</summary>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.Options.OptionsRequestBuilder OptionsPath
        {
            get => new global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.Options.OptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.WithUserFieldItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserFieldItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/user_fields/{userFieldId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.WithUserFieldItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserFieldItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/user_fields/{userFieldId}", rawUrl)
        {
        }
        /// <summary>
        /// #### Allowed for* Admins
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// #### Allowed for* Agents
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// #### Updating a Dropdown (Tagger) or Multiselect FieldDropdown and multiselect fields return an array of `custom_field_options` which specify the name, value, and order of the list of dropdown or multiselect options.Understand the following behavior when updating a dropdown or multiselect field:- All options must be passed on update. Options that are not passed will be removed. As a result, these values will be removed from any organizations.- To create a new option, pass a null `id` along with `name` and `value`.- To update an existing option, pass its `id` along with `name` and `value`.- To re-order an option, reposition it in the `custom_field_options` array relative to the other options.- To remove an option, omit it from the list of options upon update.#### Example Request```bashcurl https://{subdomain}.zendesk.com/api/v2/user_fields/{user_field_id} \  -H &quot;Content-Type: application/json&quot; -X PUT \  -d &apos;{&quot;user_field&quot;: {&quot;custom_field_options&quot;: [{&quot;id&quot;: 124, &quot;name&quot;: &quot;Option 2&quot;, &quot;value&quot;: &quot;option_2&quot;}, {&quot;id&quot;: 123, &quot;name&quot;: &quot;Option 1&quot;, &quot;value&quot;: &quot;option_1&quot;}, {&quot;id&quot;: 125, &quot;name&quot;: &quot;Option 2&quot;, &quot;value&quot;: &quot;option_3&quot;}]}}&apos; \  -v -u {email_address}/token:{api_token}```#### Allowed for* Admins
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse?> PutAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse> PutAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.UserFieldResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// #### Allowed for* Admins
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// #### Allowed for* Agents
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// #### Updating a Dropdown (Tagger) or Multiselect FieldDropdown and multiselect fields return an array of `custom_field_options` which specify the name, value, and order of the list of dropdown or multiselect options.Understand the following behavior when updating a dropdown or multiselect field:- All options must be passed on update. Options that are not passed will be removed. As a result, these values will be removed from any organizations.- To create a new option, pass a null `id` along with `name` and `value`.- To update an existing option, pass its `id` along with `name` and `value`.- To re-order an option, reposition it in the `custom_field_options` array relative to the other options.- To remove an option, omit it from the list of options upon update.#### Example Request```bashcurl https://{subdomain}.zendesk.com/api/v2/user_fields/{user_field_id} \  -H &quot;Content-Type: application/json&quot; -X PUT \  -d &apos;{&quot;user_field&quot;: {&quot;custom_field_options&quot;: [{&quot;id&quot;: 124, &quot;name&quot;: &quot;Option 2&quot;, &quot;value&quot;: &quot;option_2&quot;}, {&quot;id&quot;: 123, &quot;name&quot;: &quot;Option 1&quot;, &quot;value&quot;: &quot;option_1&quot;}, {&quot;id&quot;: 125, &quot;name&quot;: &quot;Option 2&quot;, &quot;value&quot;: &quot;option_3&quot;}]}}&apos; \  -v -u {email_address}/token:{api_token}```#### Allowed for* Admins
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.WithUserFieldItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.WithUserFieldItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.User_fields.Item.WithUserFieldItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
