// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\custom_objects\{customObjectKey}\records\{customObjectRecord-id}\attachments\{id}\download
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DownloadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/custom_objects/{customObjectKey}/records/{customObjectRecord%2Did}/attachments/{id}/download{?inline*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DownloadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/custom_objects/{customObjectKey}/records/{customObjectRecord%2Did}/attachments/{id}/download{?inline*}", rawUrl)
        {
        }
        /// <summary>
        /// Downloads the specified attachment content. Returns a redirect to the attachment&apos;s content URL.Access to malicious attachments is controlled by the `malware_access_override` setting.#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Zendesk.OpenApiClient.Models.DownloadCustomObjectRecordAttachment400Response">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Zendesk.OpenApiClient.Models.DownloadCustomObjectRecordAttachment400Response.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Downloads the specified attachment content. Returns a redirect to the attachment&apos;s content URL.Access to malicious attachments is controlled by the `malware_access_override` setting.#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder.DownloadRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/octet-stream, application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Custom_objects.Item.Records.Item.Attachments.Item.Download.DownloadRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Downloads the specified attachment content. Returns a redirect to the attachment&apos;s content URL.Access to malicious attachments is controlled by the `malware_access_override` setting.#### Allowed For* Agents
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DownloadRequestBuilderGetQueryParameters 
        {
            /// <summary>If true, the attachment content is displayed inline in the browser. If false or omitted, the attachment is downloaded as a file.</summary>
            [QueryParameter("inline")]
            public bool? Inline { get; set; }
        }
    }
}
#pragma warning restore CS0618
