// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Api.V2.Users.Item.Entitlements.Full;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Users.Item.Entitlements
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\users\{userId}\entitlements
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EntitlementsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The full property</summary>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Users.Item.Entitlements.Full.FullRequestBuilder Full
        {
            get => new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Users.Item.Entitlements.Full.FullRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Users.Item.Entitlements.EntitlementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntitlementsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/users/{userId}/entitlements", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Users.Item.Entitlements.EntitlementsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EntitlementsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/users/{userId}/entitlements", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
