// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Zendesk.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags
{
    /// <summary>
    /// Builds and executes requests for operations under \api\v2\autocomplete\tags
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TagsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/autocomplete/tags{?name*,per_page*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TagsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/v2/autocomplete/tags{?name*,per_page*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns an array of registered and recent tag names that start with the characters specified in the `name` query parameter. This includes tags where any word within the tag (separated by underscores, hyphens, spaces, or other punctuation) starts with the specified characters. You must specify at least 2 characters.#### How tag matching worksWhen tags contain delimiters like underscores, hyphens, or spaces, each word is indexed separately. A tag matches if the tag itself or any word within it starts with your search term.For example, searching for `trig` will match the tag `set_by_this_trigger` because one of its words (&quot;trigger&quot;) starts with &quot;trig&quot;. However, searching for `rigger` won&apos;t match this tag because neither the full tag nor any of its individual words (&quot;set&quot;, &quot;by&quot;, &quot;this&quot;, &quot;trigger&quot;) start with &quot;rigger&quot;.#### Autocomplete limitationsAutocomplete returns up to 15 suggestions from the most commonly used ticket tags in the last 60 days. Tags that match the prefix but aren&apos;t in that top set won&apos;t appear in the results.#### Pagination* Offset pagination onlySee [Using Offset Pagination](/api-reference/introduction/pagination/#using-offset-pagination).#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an array of registered and recent tag names that start with the characters specified in the `name` parameter. This includes tags where any word within the tag (separated by underscores, hyphens, spaces, or other punctuation) starts with the specified characters. You must specify at least 2 characters.This endpoint accepts the same parameters as the [GET method](#search-tags) but they are specified in the request body instead of the query string.#### How tag matching worksWhen tags contain delimiters like underscores, hyphens, or spaces, each word is indexed separately. A tag matches if the tag itself or any word within it starts with your search term.For example, searching for `trig` will match the tag `set_by_this_trigger` because one of its words (&quot;trigger&quot;) starts with &quot;trig&quot;. However, searching for `rigger` won&apos;t match this tag because neither the full tag nor any of its individual words (&quot;set&quot;, &quot;by&quot;, &quot;this&quot;, &quot;trigger&quot;) start with &quot;rigger&quot;.#### Autocomplete limitationsAutocomplete returns up to 15 suggestions from the most commonly used ticket tags in the last 60 days. Tags that match the prefix but aren&apos;t in that top set won&apos;t appear in the results.#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse?> PostAsync(global::Soenneker.Zendesk.OpenApiClient.Models.AutocompleteTagsPostRequest body, Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse> PostAsync(global::Soenneker.Zendesk.OpenApiClient.Models.AutocompleteTagsPostRequest body, Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse>(requestInfo, global::Soenneker.Zendesk.OpenApiClient.Models.TagsByObjectIdResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an array of registered and recent tag names that start with the characters specified in the `name` query parameter. This includes tags where any word within the tag (separated by underscores, hyphens, spaces, or other punctuation) starts with the specified characters. You must specify at least 2 characters.#### How tag matching worksWhen tags contain delimiters like underscores, hyphens, or spaces, each word is indexed separately. A tag matches if the tag itself or any word within it starts with your search term.For example, searching for `trig` will match the tag `set_by_this_trigger` because one of its words (&quot;trigger&quot;) starts with &quot;trig&quot;. However, searching for `rigger` won&apos;t match this tag because neither the full tag nor any of its individual words (&quot;set&quot;, &quot;by&quot;, &quot;this&quot;, &quot;trigger&quot;) start with &quot;rigger&quot;.#### Autocomplete limitationsAutocomplete returns up to 15 suggestions from the most commonly used ticket tags in the last 60 days. Tags that match the prefix but aren&apos;t in that top set won&apos;t appear in the results.#### Pagination* Offset pagination onlySee [Using Offset Pagination](/api-reference/introduction/pagination/#using-offset-pagination).#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns an array of registered and recent tag names that start with the characters specified in the `name` parameter. This includes tags where any word within the tag (separated by underscores, hyphens, spaces, or other punctuation) starts with the specified characters. You must specify at least 2 characters.This endpoint accepts the same parameters as the [GET method](#search-tags) but they are specified in the request body instead of the query string.#### How tag matching worksWhen tags contain delimiters like underscores, hyphens, or spaces, each word is indexed separately. A tag matches if the tag itself or any word within it starts with your search term.For example, searching for `trig` will match the tag `set_by_this_trigger` because one of its words (&quot;trigger&quot;) starts with &quot;trig&quot;. However, searching for `rigger` won&apos;t match this tag because neither the full tag nor any of its individual words (&quot;set&quot;, &quot;by&quot;, &quot;this&quot;, &quot;trigger&quot;) start with &quot;rigger&quot;.#### Autocomplete limitationsAutocomplete returns up to 15 suggestions from the most commonly used ticket tags in the last 60 days. Tags that match the prefix but aren&apos;t in that top set won&apos;t appear in the results.#### Allowed For* Agents
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Zendesk.OpenApiClient.Models.AutocompleteTagsPostRequest body, Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Zendesk.OpenApiClient.Models.AutocompleteTagsPostRequest body, Action<RequestConfiguration<global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder.TagsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Zendesk.OpenApiClient.Api.V2.Autocomplete.Tags.TagsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns an array of registered and recent tag names that start with the characters specified in the `name` query parameter. This includes tags where any word within the tag (separated by underscores, hyphens, spaces, or other punctuation) starts with the specified characters. You must specify at least 2 characters.#### How tag matching worksWhen tags contain delimiters like underscores, hyphens, or spaces, each word is indexed separately. A tag matches if the tag itself or any word within it starts with your search term.For example, searching for `trig` will match the tag `set_by_this_trigger` because one of its words (&quot;trigger&quot;) starts with &quot;trig&quot;. However, searching for `rigger` won&apos;t match this tag because neither the full tag nor any of its individual words (&quot;set&quot;, &quot;by&quot;, &quot;this&quot;, &quot;trigger&quot;) start with &quot;rigger&quot;.#### Autocomplete limitationsAutocomplete returns up to 15 suggestions from the most commonly used ticket tags in the last 60 days. Tags that match the prefix but aren&apos;t in that top set won&apos;t appear in the results.#### Pagination* Offset pagination onlySee [Using Offset Pagination](/api-reference/introduction/pagination/#using-offset-pagination).#### Allowed For* Agents
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderGetQueryParameters 
        {
            /// <summary>A substring of a tag to search for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
        }
        /// <summary>
        /// Returns an array of registered and recent tag names that start with the characters specified in the `name` parameter. This includes tags where any word within the tag (separated by underscores, hyphens, spaces, or other punctuation) starts with the specified characters. You must specify at least 2 characters.This endpoint accepts the same parameters as the [GET method](#search-tags) but they are specified in the request body instead of the query string.#### How tag matching worksWhen tags contain delimiters like underscores, hyphens, or spaces, each word is indexed separately. A tag matches if the tag itself or any word within it starts with your search term.For example, searching for `trig` will match the tag `set_by_this_trigger` because one of its words (&quot;trigger&quot;) starts with &quot;trig&quot;. However, searching for `rigger` won&apos;t match this tag because neither the full tag nor any of its individual words (&quot;set&quot;, &quot;by&quot;, &quot;this&quot;, &quot;trigger&quot;) start with &quot;rigger&quot;.#### Autocomplete limitationsAutocomplete returns up to 15 suggestions from the most commonly used ticket tags in the last 60 days. Tags that match the prefix but aren&apos;t in that top set won&apos;t appear in the results.#### Allowed For* Agents
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TagsRequestBuilderPostQueryParameters 
        {
            /// <summary>A substring of a tag to search for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("name")]
            public string? Name { get; set; }
#nullable restore
#else
            [QueryParameter("name")]
            public string Name { get; set; }
#endif
            /// <summary>Number of records to return per page.Note: Default and maximum values vary by endpoint. Check endpoint-specificdocumentation for limits.</summary>
            [QueryParameter("per_page")]
            public int? PerPage { get; set; }
        }
    }
}
#pragma warning restore CS0618
